name: do it

on:
  push:
    branches: [ "main", "dev" ]
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: 34 12 * * 06

permissions:
  contents: read

env:
  PYTHON_VERSION: ${{ vars.PYTHON_VERSION || '3.11' }}
  SAFE_TO_RUN: ${{ (github.actor == github.repository_owner) || (github.actor == vars.REPOSITORY_OWNER) }}

concurrency:
  group: ${{ github.head_ref || github.ref || github.run_id }}-${{ github.actor || github.repository_owner }}
  cancel-in-progress: ${{ (github.event_name == 'push' || github.event_name == 'schedule') && (github.actor == github.repository_owner) || (github.actor == vars.REPOSITORY_OWNER) }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Lint with flake8
        run: |
          flake8 . --count --max-complexity=10 --max-line-length=127 --statistics
  doit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install Cython
          pip install numpy~=1.26.4 pandas scikit-learn statsmodels stumpy tqdm pathos
          pip install fathon EMD-signal pathvalidate --no-deps

          #if [ -f requirements.txt ]; then pip install -r requirements.txt; fi


      - name: Lint another time with flake8
        run: |
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run tests
        if: false
        run: |
          pytest

      - name: Login to Kaggle
        if: ${{ env.SAFE_TO_RUN == 'true' }}
        uses: osbm/kaggle-login@v2.3
        with:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME || vars.KAGGLE_USERNAME || github.repository_owner }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}

      - name: Setup the dirs
        if: ${{ env.SAFE_TO_RUN == 'true' }}
        uses: Wandalen/wretry.action@v3.5.0
        with:
          command: |
            mkdir -p tmp
            mkdir -p working
            mkdir -p input
            kaggle datasets download -d ${{ env.KAGGLE_USERNAME }}/${{ env.KAGGLE_DATASET }} -p input --unzip
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME || vars.KAGGLE_USERNAME || env.KAGGLE_USERNAME || github.repository_owner }}
          KAGGLE_DATASET: ${{ secrets.KAGGLE_DATASET || vars.KAGGLE_DATASET || env.KAGGLE_DATASET || 'yahoo-finance-data' }}

      - name: Run app
        if: ${{ env.SAFE_TO_RUN == 'true' }}
        run: cd working && python ../main.py
        env:
          MAX_WORKER: ${{ env.MAX_WORKER || vars.MAX_WORKER || 2 }}
          MAX_RUNTIME: ${{ env.MAX_RUNTIME || vars.MAX_RUNTIME }}
          TRANGE_DISABLED: ${{ env.TRANGE_DISABLED || vars.TRANGE_DISABLED || 'true' }}

      - name: Upload Archive Artifact
        if: ${{ env.SAFE_TO_RUN == 'true' && always() }}
        uses: actions/upload-artifact@v4
        with:
          name: result
          path: working
          if-no-files-found: error
          retention-days: ${{ vars.ARTIFACT_RETENTION_DAYS || 60 }}


      - name: Cleanup
        if: ${{ always() }}
        run: |
          rm -rf ~/.kaggle || :
          rm -rf input || :
          rm -rf working || :
          rm -rf tmp || :
          exit 0

