name: Keep the repo alive
on:
  schedule:
    - cron: "12 22 * * *"
  push:
  fork:
  status:
  issues:

permissions:
  contents: write
  actions: write

jobs:
  keep_alive:
    name: Keep the repo alive & active
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
        with:
          use_api: true
          committer_username: ${{ vars.REPOSITORY_OWNER || github.repository_owner }}
          committer_email: ${{ vars.REPOSITORY_OWNER ||github.repository_owner }}@users.noreply.github.com
